TNG/JGiven

jgiven-core/src/main/java/com/tngtech/jgiven/annotation/Table.java, jgiven-core/src/main/java/com/tngtech/jgiven/report/model/StepFormatter.java, jgiven-core/src/test/java/com/tngtech/jgiven/format/StepFormatterTest.java, jgiven-core/src/test/java/com/tngtech/jgiven/format/TableAnnotation.java, jgiven-examples/src/test/java/com/tngtech/jgiven/examples/datatable/DataTableExamples.java
Allows one to specify the titles of table columns with an additional attribute `columnTitles` on the `@Table` annotation.
Example:
```
@Table( columnTitles = { "Name", "Email" } )
```
=> introduce columnTitles attribute for the @Table annotation

gettingstarted.md
Hello Jan,
I found this trying the example. Too bad one can't reference source code from markdown to avoid this (only Asciidoctor AFAIK). 
Best regards,
Alexander
=> reference correct class in code example

CHANGELOG.md, jgiven-core/src/main/java/com/tngtech/jgiven/annotation/IsTag.java, jgiven-core/src/main/java/com/tngtech/jgiven/config/TagConfiguration.java, jgiven-core/src/main/java/com/tngtech/jgiven/report/ReportGenerator.java, jgiven-core/src/main/java/com/tngtech/jgiven/report/html/HtmlTocWriter.java, jgiven-core/src/main/java/com/tngtech/jgiven/report/html/ScenarioHtmlWriter.java, jgiven-core/src/main/java/com/tngtech/jgiven/report/model/ReportModelBuilder.java, jgiven-core/src/main/java/com/tngtech/jgiven/report/model/Tag.java, jgiven-html5-report/src/app/app.js, jgiven-html5-report/src/app/index.html, jgiven-tests/src/test/java/com/tngtech/jgiven/report/html5/WhenHtml5Report.java
Add a new attribute `cssClass` to the `@IsTag` annotation.
```
public @interface IsTag {
String cssClass() default ""; // Or the default can come from Foundation
}
```
=> Add cssClass to @IsTag to customize tags in HTML reports

build.gradle, jgiven-core/src/test/java/com/tngtech/jgiven/report/html/ReportModelHtmlWriterTest.java, jgiven-core/src/test/java/com/tngtech/jgiven/report/text/PlainTextReporterTest.java, jgiven-tests/src/test/java/com/tngtech/jgiven/report/text/ThenPlainTextOutput.java
... to make the build work on Windows. The only other change I needed to do locally was to change `bower` to `bower.cmd` in `jgiven-html5-report\build.gradle`. Don't know yet how to make that flexible.
=> normalizing encoding and line endings in tests

CHANGELOG.md, jgiven-core/src/main/java/com/tngtech/jgiven/annotation/IsTag.java, jgiven-core/src/main/java/com/tngtech/jgiven/annotation/NotImplementedYet.java, jgiven-core/src/main/java/com/tngtech/jgiven/annotation/Pending.java, jgiven-core/src/main/java/com/tngtech/jgiven/exception/FailIfPassedException.java, jgiven-core/src/main/java/com/tngtech/jgiven/impl/StandaloneScenarioExecutor.java, jgiven-core/src/main/java/com/tngtech/jgiven/impl/intercept/InvocationMode.java, jgiven-core/src/main/java/com/tngtech/jgiven/impl/intercept/StepMethodInterceptor.java, jgiven-core/src/main/java/com/tngtech/jgiven/report/model/ExecutionStatus.java, jgiven-core/src/main/java/com/tngtech/jgiven/report/model/ExecutionStatusCalculator.java, jgiven-core/src/main/java/com/tngtech/jgiven/report/model/ReportModel.java, jgiven-core/src/main/java/com/tngtech/jgiven/report/model/ReportModelBuilder.java, jgiven-core/src/main/java/com/tngtech/jgiven/report/model/ScenarioModel.java, jgiven-core/src/main/java/com/tngtech/jgiven/report/model/StatisticsCalculator.java, jgiven-core/src/main/java/com/tngtech/jgiven/report/model/StepModel.java, jgiven-core/src/main/java/com/tngtech/jgiven/report/model/StepStatus.java, jgiven-core/src/main/java/com/tngtech/jgiven/report/text/PlainTextScenarioWriter.java, jgiven-core/src/test/java/com/tngtech/jgiven/impl/StandaloneScenarioExecutorTest.java, jgiven-core/src/test/java/com/tngtech/jgiven/report/model/ReportModelBuilderTest.java, jgiven-examples/src/test/java/com/tngtech/jgiven/examples/notimplementedyet/PendingExampleTest.java, jgiven-html5-report/src/app/css/jgivenreport.css, jgiven-html5-report/src/app/index.html, jgiven-junit/src/test/java/com/tngtech/jgiven/junit/StepsAreReportedTest.java, jgiven-tests/src/main/java/com/tngtech/jgiven/tags/FeaturePending.java, jgiven-tests/src/test/java/com/tngtech/jgiven/report/html/ReportModelHtmlWriterScenarioTest.java, jgiven-tests/src/test/java/com/tngtech/jgiven/report/text/PlainTextScenarioWriterTest.java, jgiven-tests/src/test/java/com/tngtech/jgiven/testframework/TestFrameworkExecutionTest.java
Introduce `@Pending` and make `@NotImplementedYet` deprecated
=> Pending annotation

build.gradle, jgiven-core/src/main/java/com/tngtech/jgiven/impl/util/ParameterNameUtil.java, jgiven-core/src/main/java/com/tngtech/jgiven/impl/util/ReflectionUtil.java, jgiven-java8-tests/src/test/java/com/tngtech/jgiven/tests/java8/Java8Test.java
the upgrade fixes an incompatibility with Java 8 that required that for Java 8 JGiven had to use reflection based on the -parameters option of the javac compiler. With the new Paranamer version 2.8 this is not necessary anymore.
=> Upgrade to Paranamer 2.8

.travis.yml
This adds some more options for the travis build. By caching the `.gradle` folder it saves about one minute per JDK matrix build. The total build time is down from ~20 min to ~17 min.
I considered adding a two dimensional build matrix with JDK x JUnit-Version, but then hesitated. Do you think this is useful? Will it interfere with `overallJacocoReport`?
=> speedup travis by cache/containerizing

gradle.properties, jgiven-core/src/main/java/com/tngtech/jgiven/annotation/IsTag.java, jgiven-core/src/main/java/com/tngtech/jgiven/annotation/TagHrefGenerator.java, jgiven-core/src/main/java/com/tngtech/jgiven/config/TagConfiguration.java, jgiven-core/src/main/java/com/tngtech/jgiven/impl/ScenarioModelBuilder.java, jgiven-core/src/main/java/com/tngtech/jgiven/impl/tag/DefaultTagHrefGenerator.java, jgiven-core/src/main/java/com/tngtech/jgiven/impl/tag/GoToTestHrefGenerator.java, jgiven-core/src/main/java/com/tngtech/jgiven/report/model/Tag.java, jgiven-core/src/test/java/com/tngtech/jgiven/impl/tag/GoToTestHrefGeneratorTest.java, jgiven-examples/src/test/java/com/tngtech/jgiven/examples/links/LinkExampleOneTest.java, jgiven-examples/src/test/java/com/tngtech/jgiven/examples/links/LinkExampleTwoTest.java, jgiven-examples/src/test/java/com/tngtech/jgiven/examples/links/LinkToTest.java, jgiven-examples/src/test/java/com/tngtech/jgiven/examples/links/SimpleLink.java, jgiven-html5-report/src/app/lib/reportCtrl.js, jgiven-html5-report/src/app/lib/tagService.js, jgiven-html5-report/src/main/java/com/tngtech/jgiven/report/html5/TagFile.java
I would like to be able to annotate my tests with the class of related tests.
My use case is I have a large number of tests that constitute a larger flow and would like to annotate the code with previous or next and use the annotation to create a link that takes me directly to that test in the html report.
As an enhancement I've added href and hrefGenerator to the tag system, and have modified
the HTML report to link directly to that href if present.
```java
@LinkToTest(LinkExampleTwoTest.class)
@Test
public void link_to_another_test() {
given().test_linked_to_another_test();
when().the_report_is_generated();
then().the_link_appears_in_the_report();
}
```
=> Tags in html report can be used as direct links to external websites

jgiven-core/src/main/java/com/tngtech/jgiven/impl/ScenarioModelBuilder.java, jgiven-core/src/test/java/com/tngtech/jgiven/GivenTestStep.java, jgiven-core/src/test/java/com/tngtech/jgiven/impl/ScenarioModelBuilderTest.java
I followed the same approach as for scenario description. It assumes snake_case if underscore is found. I had to play with the camelCaseToReadableText because we want it capitalised for scenario descriptions but not for steps. :)
=> support for camel case in steps (fixes #164)

jgiven-core/src/main/java/com/tngtech/jgiven/annotation/NestedSteps.java, jgiven-core/src/main/java/com/tngtech/jgiven/impl/ScenarioModelBuilder.java, jgiven-core/src/main/java/com/tngtech/jgiven/impl/StandaloneScenarioExecutor.java, jgiven-core/src/main/java/com/tngtech/jgiven/impl/intercept/NoOpScenarioListener.java, jgiven-core/src/main/java/com/tngtech/jgiven/impl/intercept/ScenarioListener.java, jgiven-core/src/main/java/com/tngtech/jgiven/impl/intercept/StepMethodHandler.java, jgiven-core/src/main/java/com/tngtech/jgiven/impl/intercept/StepMethodInterceptor.java, jgiven-core/src/main/java/com/tngtech/jgiven/report/model/InvocationMode.java, jgiven-core/src/main/java/com/tngtech/jgiven/report/model/StepModel.java, jgiven-core/src/main/java/com/tngtech/jgiven/report/model/StepStatus.java, jgiven-core/src/main/java/com/tngtech/jgiven/report/text/PlainTextScenarioWriter.java, jgiven-core/src/test/java/com/tngtech/jgiven/GivenTestStep.java, jgiven-core/src/test/java/com/tngtech/jgiven/report/text/PlainTextReporterTest.java, jgiven-examples/src/test/java/com/tngtech/jgiven/examples/nested/NestedStepsTest.java
Hello, this is an attempt to support nested steps.
I had to change a few things around ScenarioModelBuilder to keep a stack of steps so we can add a nested step to the right parent and supporting multilevel nesting. 
As for the report, I have just done it for the plain text report. Note that the nested steps are for report purposes only, i.e. the step status, duration, attachments, etc, are really kept at the top level only. Otherwise it gets too complicated.
If this is accepted, a separate issue should be created for html5 report maybe with a collapsible widget
=> implemented nested steps #17 (+ text report only)

jgiven-html5-report/src/main/java/com/tngtech/jgiven/report/html5/Html5ReportGenerator.java
This occurs when running on an OS without UTF-8 as default charset (i.e. windows machines). This problem has been introduced in #186. 
I found it hard to provide an automated test for this. Therefore I looked at JGiven's own report before and after regarding the German test cases. 
Please double-check if this still works on UTF-8 (well, it should, shouldn't it?)
=> ensure that contents are encoded utf-8 for pako lib

jgiven-html5-report/src/app/index.html
I have a parameterized test case that is not shown as a table (due to different test steps depending on the parameters). 
What I see in HTML5 report of the current version (0.11.3): For every case all attachments of all cases are shown (= multiple paperclips on a single step).
What I want: Only the attachments of the current case should to be shown (without the index). 
This change fixes it for me. I'm not sure if this is the optimal code change as I'm not familiar with AngularJS - but it works for me. Please feel free to refactor.
I'm looking forward to a patch release if possible.
=> don't show multiple indexed attachments when cases are not shown as table

CHANGELOG.md, jgiven-core/src/main/java/com/tngtech/jgiven/CurrentScenario.java, jgiven-core/src/main/java/com/tngtech/jgiven/annotation/TagDescriptionGenerator.java, jgiven-core/src/main/java/com/tngtech/jgiven/annotation/TagHrefGenerator.java, jgiven-core/src/main/java/com/tngtech/jgiven/impl/ScenarioBase.java, jgiven-core/src/main/java/com/tngtech/jgiven/impl/ScenarioExecutor.java, jgiven-core/src/main/java/com/tngtech/jgiven/impl/ScenarioModelBuilder.java, jgiven-core/src/main/java/com/tngtech/jgiven/impl/StandaloneScenarioExecutor.java, jgiven-core/src/main/java/com/tngtech/jgiven/impl/intercept/NoOpScenarioListener.java, jgiven-core/src/main/java/com/tngtech/jgiven/impl/intercept/ScenarioListener.java, jgiven-core/src/test/java/com/tngtech/jgiven/impl/ScenarioModelBuilderTest.java, jgiven-examples/src/test/java/com/tngtech/jgiven/examples/tags/DynamicTags.java, jgiven-examples/src/test/java/com/tngtech/jgiven/examples/tags/StepTags.java, jgiven-junit/src/test/java/com/tngtech/jgiven/junit/ScenarioExecutionTest.java, jgiven-junit/src/test/java/com/tngtech/jgiven/junit/TagAnnotationTest.java, jgiven-junit/src/test/java/com/tngtech/jgiven/junit/test/GivenTaggedTestStep.java, jgiven-junit/src/test/java/com/tngtech/jgiven/junit/test/GivenTestStep.java
This commit allows adding tags dynamically to a scenario at runtime.
Furthermore, it implicitly fixes an issue where nested tags, description
and href would not be evaluated if ignoreValue was set to true.
fixes #172
=> Allow adding tags dynamically.

CHANGELOG.md, jgiven-core/src/main/java/com/tngtech/jgiven/annotation/As.java, jgiven-core/src/main/java/com/tngtech/jgiven/annotation/AsProvider.java, jgiven-core/src/main/java/com/tngtech/jgiven/impl/ScenarioModelBuilder.java, jgiven-core/src/main/java/com/tngtech/jgiven/impl/params/DefaultAsProvider.java, jgiven-core/src/main/java/com/tngtech/jgiven/impl/util/WordUtil.java, jgiven-core/src/main/java/com/tngtech/jgiven/report/model/ReportModel.java, jgiven-core/src/test/java/com/tngtech/jgiven/GivenTestStep.java, jgiven-core/src/test/java/com/tngtech/jgiven/impl/ScenarioModelBuilderTest.java
This change extends the @As annotation for step / stage methods and classes
with an AsProvider provider() method to allow a more flexible way of
customizing the result.
fixes #189
=> Extend @As with a provider mechanism.

CHANGELOG.md, docs/getting_started.adoc, jgiven-examples/src/test/java/com/tngtech/jgiven/examples/userguide/UsingRulesTest.java, jgiven-junit/src/main/java/com/tngtech/jgiven/junit/ScenarioExecutionRule.java, jgiven-junit/src/test/java/com/tngtech/jgiven/junit/OnlyRulesTest.java
The JUnit rules can now be used standalone. This means that it is possible to use JGiven without deriving from the `ScenarioTest` class.
=> Use JGiven by just using JUnit rules

build.gradle, jgiven-maven-plugin/build.gradle
As a contributor I want to use `gradlew publishToMavenLocal` so I can test my contributions easily together with my local projects.
Therefore I added _maven-publish_. As I'm unexperienced with gradle, I might have missed something. But it now works for me.
Please advise if changes are necessary.
=> allow `gradlew publishToMavenLocal`

jgiven-core/src/main/java/com/tngtech/jgiven/impl/Config.java, jgiven-gradle-plugin/build.gradle, jgiven-gradle-plugin/src/main/java/com/tngtech/jgiven/gradle/JGivenPlugin.java, jgiven-gradle-plugin/src/main/java/com/tngtech/jgiven/gradle/JGivenReport.java, jgiven-gradle-plugin/src/main/java/com/tngtech/jgiven/gradle/JGivenTaskExtension.java, jgiven-gradle-plugin/src/test/java/com/tngtech/jgiven/gradle/JGivenPluginTest.java, jgiven-gradle-plugin/src/test/resources/SimpleScenario.java, settings.gradle
This would fix #98.
The plugin currently adds a `jgiven<Test Task name>Report` task
for each test task and generates the report (if JGiven JSON files have been generated)
to `build/reports/jgiven/<Test Task Name>`.
Things which still need some work:
- Add the possibility to generate other reports apart from the html
report
- Add some more tests regarding up to date checking
- Should it be possible to generate one report for all tests executed
in
- a multimodule build
- different test tasks
- Use the built version of JGiven in the tests instead of the last
released version
- Polish the code
=> Add initial version of JGiven Gradle plugin

jgiven-html5-report/src/main/java/com/tngtech/jgiven/report/html5/Html5AttachmentGenerator.java, jgiven-html5-report/src/test/java/com/tngtech/jgiven/report/html5/Html5AttachmentGeneratorTest.java
Instead of creating files for text and image media types, this now creates attachments for all media types.
The the binary vs. text content will be determined by the _binary_ flag of the attachment. The file extension will be determined by the media type.
A new test in Html5AttachmentGeneratorTest ensure that both text and binary files are created.
Closes #228
=> create files for all attachments

jgiven-examples/src/test/java/com/tngtech/jgiven/examples/pancakes/test/SpringPanCakeScenarioTest.java, jgiven-examples/src/test/java/com/tngtech/jgiven/examples/pancakes/test/TestSpringConfig.java, jgiven-examples/src/test/java/com/tngtech/jgiven/examples/pancakes/test/steps/WhenCook.java, jgiven-spring/build.gradle, jgiven-spring/src/main/java/com/tngtech/jgiven/integration/spring/InternalSimpleSpringScenarioTest.java, jgiven-spring/src/main/java/com/tngtech/jgiven/integration/spring/InternalSpringScenarioTest.java, jgiven-spring/src/main/java/com/tngtech/jgiven/integration/spring/SimpleSpringRuleScenarioTest.java, jgiven-spring/src/main/java/com/tngtech/jgiven/integration/spring/SpringRuleScenarioTest.java, jgiven-spring/src/main/java/com/tngtech/jgiven/integration/spring/SpringScenarioTest.java, jgiven-spring/src/test/java/com/tngtech/jgiven/integration/spring/test/SimpleSpringRuleScenarioTestTest.java, jgiven-spring/src/test/java/com/tngtech/jgiven/integration/spring/test/SimpleTestSpringSteps.java, jgiven-spring/src/test/java/com/tngtech/jgiven/integration/spring/test/SpringRuleScenarioTestTest.java, jgiven-spring/src/test/java/com/tngtech/jgiven/integration/spring/test/SpringRuleScenarioWithDataProviderTest.java, jgiven-spring/src/test/java/com/tngtech/jgiven/integration/spring/test/TestBean.java
Use Spring's @Rule support added in v4.2 for the SpringScenarioTest instead of using SpringJUnit4ClassRunner.
Enables the use of custom JUnit runners like DataProviderRunner (see example test).
=> Use Spring's @Rule support instead of @RunWith(SpringJunit4ClassRunner)

jgiven-tests/src/test/java/com/tngtech/jgiven/report/html5/Html5ReportGeneratorTest.java
unfortunately the windows file separator is a backslash that serves as escape character and therefore needs to be escaped.
=> fix windows build problem in Html5ReportGeneratorTest

jgiven-core/src/main/java/com/tngtech/jgiven/config/TagConfiguration.java, jgiven-core/src/main/java/com/tngtech/jgiven/impl/ScenarioModelBuilder.java, jgiven-core/src/main/java/com/tngtech/jgiven/report/model/Tag.java, jgiven-core/src/test/java/com/tngtech/jgiven/impl/ScenarioModelBuilderTest.java, jgiven-html5-report/src/app/lib/reportCtrl.js, jgiven-html5-report/src/app/lib/tagService.js, jgiven-html5-report/src/app/lib/util.js, jgiven-html5-report/src/main/java/com/tngtech/jgiven/report/html5/TagFile.java, jgiven-html5-report/src/test/app/tagServiceTest.js, jgiven-junit/src/test/java/com/tngtech/jgiven/junit/ScenarioExecutionTest.java, jgiven-junit/src/test/java/com/tngtech/jgiven/junit/StepsAreReportedTest.java, jgiven-junit/src/test/java/com/tngtech/jgiven/junit/TagAnnotationTest.java, jgiven-junit/src/test/java/com/tngtech/jgiven/junit/tags/AbstractScenarioForTestingTagInheritance.java, jgiven-tests/src/test/java/com/tngtech/jgiven/report/model/GivenReportModel.java, jgiven-tests/src/test/java/com/tngtech/jgiven/testframework/TestFrameworkExecutionTest.java
In our project we use very many tags, and we order them in hierarchies and with inner classes. Sometimes inner classes have the same names (as they are the leaves of our tree).  This is currently not supported by JGiven, as it uses the class' simpleName to index the tags. I know that this is to some extent documented in @IsTag#name - but it seems to be a bit outdated as it talks about "type name".
This tries to introduce the full class name to derive the IDs of the tags, while preserving the existing functionality to use the simple name as the default name of the tag. The ID will only be used for the internal indexing, and will not be shown to the user.
I've tested this with the HTML5 report and it works for me AFAICS. Let me know what you think - I wonder if it breaks functionality or …
=> use full class name as ID of a tag

CHANGELOG.md, jgiven-core/src/main/java/com/tngtech/jgiven/annotation/ExpectedScenarioState.java, jgiven-core/src/main/java/com/tngtech/jgiven/annotation/ScenarioState.java, jgiven-core/src/main/java/com/tngtech/jgiven/exception/JGivenMissingRequiredScenarioStateException.java, jgiven-core/src/main/java/com/tngtech/jgiven/impl/inject/ScenarioStateField.java, jgiven-core/src/main/java/com/tngtech/jgiven/impl/inject/ValueInjector.java, jgiven-junit/src/test/java/com/tngtech/jgiven/junit/RequiredScenarioStateTest.java
This commit adds a new boolean attribute "required" to both
ScenarioState and ExpectedScenarioState. If set to true on a
field within a stage, corresponding tests will fail automatically
if the state hasn't been provided.
fixes #255
=> Added required attribute to ScenarioState.

jgiven-maven-plugin/build.gradle
this extends the CrossPlatformExec concept for other modules to the maven plugin
=> Enable building Maven plugin on Windows

jgiven-html-app/src/js/util.js, jgiven-html-app/src/test/utilTest.js, jgiven-tests/src/test/java/com/tngtech/jgiven/report/html5/Html5AppTest.java
* removed ambiguity for extended description parsing in js
* added same tests in js and java as for the As Description
The parsing now absorbs `$argumentNotKnown` like the **As** and **Case** Descriptions. It follows the same rules as these descriptions, except the appending of unused argument.
=> refactored extended description parsing

docs/report_generation.adoc
Given a user's question in #316 about parameters for report generation, I updated the documentation regarding the Maven plugin. 
This duplicates the documentation available in the source code and the maven plugin, but this might be easier to find for the users.
=> Document Maven report options

docs/report_generation.adoc
It has taken some time for me to actually find this configuration (custom target directory for json files). I added a snippet to the documentation for everybody who might look for something similar.
=> Add doc for json report configuration

jgiven-html5-report/src/main/java/com/tngtech/jgiven/report/html5/Html5ReportGenerator.java
With using a logger created for this class, the log messages will appear associated with the class Html5ReportGenerator in the logfiles.
=> fixed logger to use in Html5ReportGenerator

jgiven-spring/src/main/java/com/tngtech/jgiven/integration/spring/JGivenStage.java, jgiven-spring/src/test/java/com/tngtech/jgiven/integration/spring/test/SpringRuleFreshInstanceForEachDataproviderTest.java, jgiven-spring/src/test/java/com/tngtech/jgiven/integration/spring/test/SpringRuleFreshInstanceForEachTestTest.java, jgiven-spring/src/test/java/com/tngtech/jgiven/integration/spring/test/proxy/ThenNewInstanceStage.java
There is added JavaDoc and two test cases. I needed to store a reference to the previous step, so I added a private static field to make it work.
Any ideas how to improve this? Should the documentation be enhanced?
If the answers are "no" it's ready to be merged from my point of view.
closes #362
=> @JGivenStage enforces prototype mode to ensure a fresh instance 

CHANGELOG.md, jgiven-core/src/main/java/com/tngtech/jgiven/impl/intercept/StepInterceptorImpl.java, jgiven-core/src/main/java/com/tngtech/jgiven/report/model/InvocationMode.java, jgiven-core/src/test/java/com/tngtech/jgiven/impl/ScenarioExecutorTest.java
Better late than never :wink: 
This PR changes JGiven's behavior with respect to methods that should not be intercepted (annotated with `@DoNotIntercept` or methods of `java.lang.Object`). These methods will now not trigger a change of the active stage and hence not trigger any `@AfterStage` methods.
I have thought about adding a new annotation to solve my issue #266, but in fact I don't see the use of those methods triggering any JGiven behavior.
This is pretty much the behavior I had expected from `@DoNotIntercept` anyway, to have absolutely no side effects within JGiven.
If I have missed a point here (I don't know the code base very well), let me know. But since all tests seemed to pass, I figured that there was no specific reason for the old behavior.
Resolves: #266
=> Make @DoNotIntercept not trigger stage changes.

docs/getting_started.adoc, docs/junit5.adoc, jgiven-core/src/main/java/com/tngtech/jgiven/base/DualScenarioTestBase.java, jgiven-junit/src/main/java/com/tngtech/jgiven/junit/DualScenarioTest.java, jgiven-junit/src/main/java/com/tngtech/jgiven/junit/SimpleScenarioTest.java, jgiven-junit5/src/main/java/com/tngtech/jgiven/junit5/DualScenarioTest.java, jgiven-spring/src/main/java/com/tngtech/jgiven/integration/spring/DualSpringRuleScenarioTest.java, jgiven-spring/src/main/java/com/tngtech/jgiven/integration/spring/DualSpringScenarioTest.java, jgiven-spring/src/main/java/com/tngtech/jgiven/integration/spring/InternalDualSpringScenarioTest.java, jgiven-testng/src/main/java/com/tngtech/jgiven/testng/DualScenarioTest.java
see #388 
Motivation: keep steps for given and when in same stage so you can easily build tests that build on each other like 
```
given().doA();
when().doB();
then().assertState();
```
and
```
given().doA().and().doB();
when().doC();
then().assertState();
```
Naming things was the hard part, I came up with DualScenarioTest ... if you are generally fine with the idea, I will continue adding tests and docs.
=> introduce DualScenarioTest

jgiven-core/src/main/java/com/tngtech/jgiven/impl/ScenarioExecutor.java, jgiven-core/src/main/java/com/tngtech/jgiven/impl/intercept/StepInterceptorImpl.java, jgiven-testng/src/main/java/com/tngtech/jgiven/testng/ScenarioTestListener.java, jgiven-testng/src/test/java/com/tngtech/jgiven/testng/PendingTest.java, jgiven-testng/src/test/java/com/tngtech/jgiven/testng/RetryTest.java, jgiven-testng/src/test/java/com/tngtech/jgiven/testng/TestNgTest.java, jgiven-tests/src/test/java/com/tngtech/jgiven/junit/JUnitExecutorTest.java, jgiven-tests/src/test/java/com/tngtech/jgiven/testframework/TestFrameworkExecutionTest.java, jgiven-tests/src/test/java/com/tngtech/jgiven/testng/TestNgExecutor.java
JGiven does not interact well with TestNG in case exceptions are thrown in step methods. Normally JGiven catches all exceptions to be able to report the following steps of a scenario and rethrows the exception at the end of a scenario. In JUnit this works as expected. In TestNG, however, the hook for JGiven comes too late to rethrow the exception. Thus TestNG always treats failing scenarios as success. This PR fixes this by not catching exceptions in steps anymore. The disadvantage of this is that the steps following a failed step cannot be reported anymore.
=> Change exception handling for TestNG (#312)

jgiven-gradle-plugin/build.gradle, jgiven-gradle-plugin/src/main/java/com/tngtech/jgiven/gradle/JGivenPlugin.java, jgiven-gradle-plugin/src/test/groovy/com/tngtech.jgiven.gradle/JGivenPluginShould.groovy
=> Fix JGiven Plugin to be a cacheable task

jgiven-core/src/test/java/com/tngtech/jgiven/GivenTestStep.java, jgiven-core/src/test/java/com/tngtech/jgiven/WhenTestStep.java, jgiven-core/src/test/java/com/tngtech/jgiven/impl/ScenarioModelBuilderTest.java, jgiven-examples/src/test/java/com/tngtech/jgiven/examples/FailingScenarioTest.java, jgiven-examples/src/test/java/com/tngtech/jgiven/examples/parameters/ParameterFormattingTest.java, jgiven-junit/src/test/java/com/tngtech/jgiven/junit/StepsAreReportedTest.java, jgiven-junit/src/test/java/com/tngtech/jgiven/junit/test/BeforeAfterTestStage.java, jgiven-junit/src/test/java/com/tngtech/jgiven/junit/test/GivenTestStep.java, jgiven-junit/src/test/java/com/tngtech/jgiven/junit/test/ThenTestStep.java, jgiven-junit/src/test/java/com/tngtech/jgiven/junit/test/WhenTestStep.java, jgiven-tests/src/test/java/com/tngtech/jgiven/report/WhenReportGenerator.java, jgiven-tests/src/test/java/com/tngtech/jgiven/report/text/ThenPlainTextOutput.java
Tiny beauty PR. 
I removed some methods that were unused and added a return value to methods that would spawn a warning about having no return value in the logs.
=> Remove cause for does not adhere to convention warning

docs/stages.adoc, jgiven-core/src/main/java/com/tngtech/jgiven/annotation/FillerWord.java, jgiven-core/src/main/java/com/tngtech/jgiven/impl/ScenarioModelBuilder.java, jgiven-core/src/main/java/com/tngtech/jgiven/impl/SentenceBuilder.java, jgiven-core/src/main/java/com/tngtech/jgiven/report/model/StepModel.java, jgiven-core/src/main/java/com/tngtech/jgiven/report/model/Word.java, jgiven-core/src/test/java/com/tngtech/jgiven/GivenTestStep.java, jgiven-core/src/test/java/com/tngtech/jgiven/impl/ScenarioModelBuilderTest.java, jgiven-examples/src/test/java/com/tngtech/jgiven/examples/pancakes/test/ExtendedVocabularyPanCakeTest.java, jgiven-examples/src/test/java/com/tngtech/jgiven/examples/userguide/ExtendedVocabularyTest.java
Hi @janschaefer and @l-1squared.
I have the first PR ready. In addition to the new `@FillerWord` concept I've also added `@Punctuation`, let me know what you think?
Richard
=> Implementation of "Filler Words"

build.gradle, jgiven-html-app/build.gradle
Using the `com.github.node-gradle.node` plugin we get OS independence out of the box. I also set `node.download = true` to automatically download and install a build-local version of NPM without relying on a globally installed distribution.
=> replace custom `npm` execution by Gradle Node plugin

build.gradle, example-projects/junit5/build.gradle, scripts/release.sh
The changes needed to enables an automatic OSS-Release via Github include
- Provide credentials from environment variables as there is no gradle.properties
- When triggered by a CI workflow the release should always happen.
- gradle plugin test should use the artifact on the oss.sonatype staging repo similar to the maven plugin test
=> Enable automatic OSS-Release

scripts/release.sh
publishToMaven didn't produce artifacts on sonatype and pure publish seems to what everyone else does.
=> Issue-478: fix publish command

build.gradle, scripts/release.sh
When using the catchall 'publish' tasks, gradle would execute the publication to maven and the publication to gradle in the same run. Since these two task produce a publication with the exact same coordinates, but different metadata (pom vs no pom) the latter would overwrite the former leading to a failure of the sonatype pom verification.
I have checked that the "multiple publication message under same coordinates" does not appear anymore, also I have checked that the "publishPlugins" task is not excluded by the changes to the signing plugin (in fact it does not seem that the signing requirement is checked under "publishPlugins")
=> Issue-478: separate maven from gradle plugin publication

jgiven-spring-junit4/src/test/java/com/tngtech/jgiven/integration/spring/test/AdditionalStageTest.java, jgiven-spring-junit5/src/main/java/com/tngtech/jgiven/integration/spring/junit5/DualSpringScenarioTest.java, jgiven-spring-junit5/src/main/java/com/tngtech/jgiven/integration/spring/junit5/SimpleSpringScenarioTest.java, jgiven-spring-junit5/src/main/java/com/tngtech/jgiven/integration/spring/junit5/SpringScenarioTest.java, jgiven-spring-junit5/src/test/java/com/tngtech/jgiven/integration/spring/junit5/test/AdditionalStageTest.java
Note that the JUnit5 Extensions have to be executed in the correct order, meaning the SpringExtension must run before the JGivenExtension. This is now enforced. Unfortunately, the original JUnit5 ScenarioTest (and similar) cannot be used any longer because they already contain the JGivenExtension.
Signed-off-by: Fabian Kneißl <fabian.kneissl@tngtech.com>
Note that it would be good to also merge #493 so that the tests are actually executed :)
=> Fixes #494, i.e. the bug that additional stages in JUnit5 are not injected as Spring Beans.

scripts/release.sh
Currently the maven plugin build fails, because its maven build tries to collect the jgiven artifacts of the version being released from maven central, which cannot go well. If there is a copy of them in the local repo the build should work
=> Issue-478: also publish artifacts to local repository on release

scripts/release.sh, scripts/release_functions.sh, scripts/test_release_functions.sh
It turns out that there is no way to return a string or an array with elements that themselves contain spaces in a way that bash will interpret the elements correctly (i.e. var1, var 2, var3 -> var1, var, 2, var3). The solution is to use bash's nameref feature. This allows a function to write to a variable directly without knowing the actual variable name.
=> Issue-478: ensure the property finders output is handled correctly

build.gradle
Asiidoc used the directory from where the corresponding gradle task was executed as the base directory to resolve relative incluedes. Naturally this led to paths that could not be resolved. Also bump version to 3.0.0
=> Issue-478: set asciidoc base dir manually and bump version

renovate.json
Because, otherwise the DCO check will always fail
=> Add signoff message for renovate PRs

renovate.json
Given the reports from the still failing DCO check, this should be the correct way to do it
=> add correct signoff message

renovate.json
The massive amount of Renovate PRs generate a lot of noise. Out of the options to reduce that noise, I chose to first just group automerge PR and limit the time at which the will be opened. The most powerful noise-reduction feature, branch-automerge, is currently incompatible with the repos branch protection settings, also I am not yet sure for which types of updates I should activate that.
=> Issue-558: group and schedule Renovate PRs

settings.gradle
the jcenter and bintray repocitories are scheduled to close down at the end of may 2021.
=> remove jcenter repo from built

jgiven-core/src/main/java/com/tngtech/jgiven/report/model/ScenarioCaseModel.java, jgiven-core/src/main/java/com/tngtech/jgiven/report/model/StepModel.java, jgiven-core/src/main/java/com/tngtech/jgiven/report/text/PlainTextScenarioWriter.java, jgiven-html5-report/src/test/java/com/tngtech/jgiven/report/html5/Html5AttachmentGeneratorTest.java
Fix for issue #366 nested steps not showing attachments in html report
Added recursive visiting of nested steps in ScenarioCaseModel so that all attachments of nested steps will be found and shown in report.
PlainTextScenarioWriter had to be adjusted so that it uses the nested steps found by the visitor for the plain text report. In order to work as before two new attributes were added to StepModel.
=> Fix for issue #366 nested steps not showing attachments in html report

jgiven-core/src/main/java/com/tngtech/jgiven/impl/ScenarioModelBuilder.java, jgiven-core/src/main/java/com/tngtech/jgiven/impl/tag/TagCreator.java, jgiven-core/src/test/java/com/tngtech/jgiven/impl/ScenarioModelBuilderTest.java, jgiven-core/src/test/java/com/tngtech/jgiven/impl/tag/TagClassCollection.java, jgiven-core/src/test/java/com/tngtech/jgiven/impl/tag/TagCreatorTest.java
The tag creation methods are strongly dependent on each other but apart from putting the end result into the models have nothing to do with model building.
They therefore should end up in their own class that is independent of the models.
=> extract tag creation tasks from scenario model builder and refactor

jgiven-core/src/test/java/com/tngtech/jgiven/impl/ProxyClassPerformanceTest.java
Previously the test failed for a scenario where the reported memory usage would be constant but increased for the last recorded item. In such a case the reported growth would not be 0, but looking at the record would reveal no continuous growth.
Therefore we now allow the last item in the record to be an increment by 1.
=> Increase growth cutoff for ProxyClassPerformanceTest

jgiven-maven-plugin/src/main/java/com/tngtech/jgiven/maven/JGivenReportMojo.java
for running maven builds in parallel.  Regarding to https://github.com/TNG/JGiven/issues/823
Solution gained from:  
https://cwiki.apache.org/confluence/display/MAVEN/Parallel+builds+in+Maven+3  
and   
https://stackoverflow.com/questions/24448623/how-to-mark-maven-plugin-threadsafe
=> Annotate maven plugins mojo with threadSafe true

jgiven-junit/build.gradle, jgiven-junit/src/test/java/com/tngtech/jgiven/junit/concurrency/JUnit4InheritedParallelizationTest.java, jgiven-junit/src/test/java/com/tngtech/jgiven/junit/concurrency/JUnit4InjectedParallelizationTest.java, jgiven-junit/src/test/java/com/tngtech/jgiven/junit/concurrency/Stages.java
The package with the dodgy name is actually a recommendation from the JUnit 4 site itself, therefore
I opted to use it here.
Contrary to JUnit5 I opted against having a second method in the classes, because paralellization works on class level only anyway which means that the method just lost what little use they had.
=> Issue-829: Write Parallel JUnit 4 tests

.github/workflows/jgiven_align_gh_pages.yml
Previously the repository did not checkout a single branch but actually a single commit, which it made into a unique ref for its own repo. Consequently, when attempting to rebase the entire history of gh-pages onto that commit the rebase would fail, because the base in the repo wasn't the actual master branch but only its latest commit which resulted in an unfitting history of that commit and a failing rebase.
Now that we check out everything from the start, this should work fine.
=> Checkout actions fetches whole repository

jgiven-core/src/test/java/com/tngtech/jgiven/impl/tag/TestTagGenerator.java
That line generated well over 1000 lines of nonsense statements in the log.
=> Removed print statement

jgiven-maven-plugin/build.gradle
Apparently the previous fix prevented gradle from ever registering the dependency between tasks. Or it did not matter for task scheduling any more. Thus this update
=> Fix fixing the fix

.github/workflows/jgiven_examples_build.yml, CHANGELOG.md, build.gradle, scripts/validate_poms.sh
The error happens here, because we write the "compileOnly" dependencies manually. In case of "compileOnly" dependencies gradle does not resolve any version. So for the JUnit5 dependencies gradle writes an empty version tag, producing an invalid pom.
However, gradle does correctly add the junit-bom to the pom as dependency management so that there should not be any version in that dependency in the first place.
=> Issue-1013: only write a version when there is a version to write

README.md
Route of build status had to be changed, because the build provider identified the need for a breaking change in its service. Details see here: https://github.com/badges/shields/issues/8671
=> Fix broken build shield

scripts/publishAsciidoc.sh, scripts/publishJGivenReports.sh, scripts/publishJGivenSnapshotReports.sh, scripts/publishJavadoc.sh
This should simplify a release from a release branch in case a we need to select commits
=> Issue-802: Release script return to previous branch

_posts/2014-09-08-JavaAktuell.markdown, _posts/2015-07-04-video-on-bigtechday8.markdown, docs.md, index.md
This PR fixes some links on https://jgiven.org/ (i.e. branch `gh-pages`).
The [old link](https://media.techcast.cloud//bigtechday8/maffei-1345) to the video of the Big Techday talk is not available anymore.
=> fix link of Big Techday talk & Java aktuell

README.md
The [old link](https://media.techcast.cloud//bigtechday8/maffei-1345) is not available anymore.
=> fix link of Big Techday talk
